### ISSUE TITLE
Migration problem with foreignkey constraints

### ISSUE THREAD

**Issue by RobinLjungqvist** [mondeun/Real-Estate#1]
Using StartUp project 'Real Estate'.
Using NuGet project 'Real Estate'.
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Target database is: 'RealEstateSystemDB' (DataSource: ., Provider: System.Data.SqlClient, Origin: Configuration).
No pending explicit migrations.
Applying automatic migration: 201604261109038_AutomaticMigration.
CREATE TABLE [dbo].[Person]([PersonID] [int] NOT NULL IDENTITY,
    [ZipCodeRefID] [int] NOT NULL,
    [CityRefID] [int] NOT NULL,
    [FirstName] [nvarchar]%28max%29,
    [LastName] [nvarchar]%28max%29,
    [Pnr] [int] NOT NULL,
    [Address] [nvarchar]%28max%29,
    [Email] [nvarchar]%28max%29,
    [OfficeID] [int],
    [ViewingID] [int],
    [Discriminator] [nvarchar]%28128%29 NOT NULL,
    CONSTRAINT [PK_dbo.Person] PRIMARY KEY %28[PersonID]%29)
CREATE TABLE [dbo].[City]([CityID] [int] NOT NULL IDENTITY,
    [CityName] [nvarchar]%28max%29,
    CONSTRAINT [PK_dbo.City] PRIMARY KEY %28[CityID]%29)
CREATE TABLE [dbo].[Office]([OfficeID] [int] NOT NULL IDENTITY,
    [OfficeName] [nvarchar]%28max%29,
    [Address] [nvarchar]%28max%29,
    [City_CityID] [int],
    [ZipCode_ZipCodeID] [int],
    CONSTRAINT [PK_dbo.Office] PRIMARY KEY %28[OfficeID]%29)
CREATE TABLE [dbo].[ZipCode]([ZipCodeID] [int] NOT NULL IDENTITY,
    [zipCode] [nvarchar]%28max%29,
    CONSTRAINT [PK_dbo.ZipCode] PRIMARY KEY %28[ZipCodeID]%29)
CREATE TABLE [dbo].[Viewing]([ViewingID] [int] NOT NULL IDENTITY,
    [RealEstateObjectID] [int] NOT NULL,
    [PersonID] [int] NOT NULL,
    [AgentRefID] [int] NOT NULL,
    [ViewingStart] [datetime] NOT NULL,
    [ViewingStop] [datetime] NOT NULL,
    [NbrOfCustomerPerViewing] [int] NOT NULL,
    CONSTRAINT [PK_dbo.Viewing] PRIMARY KEY %28[ViewingID]%29)
CREATE TABLE [dbo].[RealEstateObject]([RealEstateObjectID] [int] NOT NULL IDENTITY,
    [Contract] [int] NOT NULL,
    [EstateType] [int] NOT NULL,
    [AgentRefID] [int],
    [sqm] [int] NOT NULL,
    [Address] [nvarchar]%28max%29,
    [CityRefID] [int] NOT NULL,
    [ZipCodeRefID] [int] NOT NULL,
    [DateOnMarket] [datetime] NOT NULL,
    [SaleDate] [datetime],
    [Sold] [bit] NOT NULL,
    CONSTRAINT [PK_dbo.RealEstateObject] PRIMARY KEY %28[RealEstateObjectID]%29)
CREATE TABLE [dbo].[ViewingCustomer]([Viewing_ViewingID] [int] NOT NULL,
    [Customer_PersonID] [int] NOT NULL,
    CONSTRAINT [PK_dbo.ViewingCustomer] PRIMARY KEY %28[Viewing_ViewingID], [Customer_PersonID]%29)
CREATE INDEX [IX_ZipCodeRefID] ON [dbo].[Person]([ZipCodeRefID])
CREATE INDEX [IX_CityRefID] ON [dbo].[Person]([CityRefID])
CREATE INDEX [IX_OfficeID] ON [dbo].[Person]([OfficeID])
CREATE INDEX [IX_City_CityID] ON [dbo].[Office]([City_CityID])
CREATE INDEX [IX_ZipCode_ZipCodeID] ON [dbo].[Office]([ZipCode_ZipCodeID])
CREATE INDEX [IX_RealEstateObjectID] ON [dbo].[Viewing]([RealEstateObjectID])
CREATE INDEX [IX_AgentRefID] ON [dbo].[Viewing]([AgentRefID])
CREATE INDEX [IX_AgentRefID] ON [dbo].[RealEstateObject]([AgentRefID])
CREATE INDEX [IX_CityRefID] ON [dbo].[RealEstateObject]([CityRefID])
CREATE INDEX [IX_ZipCodeRefID] ON [dbo].[RealEstateObject]([ZipCodeRefID])
CREATE INDEX [IX_Viewing_ViewingID] ON [dbo].[ViewingCustomer]([Viewing_ViewingID])
CREATE INDEX [IX_Customer_PersonID] ON [dbo].[ViewingCustomer]([Customer_PersonID])
ALTER TABLE [dbo].[Person] ADD CONSTRAINT [FK_dbo.Person_dbo.City_CityRefID] FOREIGN KEY ([CityRefID]) REFERENCES [dbo].[City]([CityID]) ON DELETE CASCADE
ALTER TABLE [dbo].[Person] ADD CONSTRAINT [FK_dbo.Person_dbo.ZipCode_ZipCodeRefID] FOREIGN KEY ([ZipCodeRefID]) REFERENCES [dbo].[ZipCode]([ZipCodeID]) ON DELETE CASCADE
ALTER TABLE [dbo].[Person] ADD CONSTRAINT [FK_dbo.Person_dbo.Office_OfficeID] FOREIGN KEY ([OfficeID]) REFERENCES [dbo].[Office]([OfficeID]) ON DELETE CASCADE
ALTER TABLE [dbo].[Office] ADD CONSTRAINT [FK_dbo.Office_dbo.City_City_CityID] FOREIGN KEY ([City_CityID]) REFERENCES [dbo].[City]([CityID])
ALTER TABLE [dbo].[Office] ADD CONSTRAINT [FK_dbo.Office_dbo.ZipCode_ZipCode_ZipCodeID] FOREIGN KEY ([ZipCode_ZipCodeID]) REFERENCES [dbo].[ZipCode]([ZipCodeID])
ALTER TABLE [dbo].[Viewing] ADD CONSTRAINT [FK_dbo.Viewing_dbo.Person_AgentRefID] FOREIGN KEY ([AgentRefID]) REFERENCES [dbo].[Person]([PersonID]) ON DELETE CASCADE
ALTER TABLE [dbo].[Viewing] ADD CONSTRAINT [FK_dbo.Viewing_dbo.RealEstateObject_RealEstateObjectID] FOREIGN KEY ([RealEstateObjectID]) REFERENCES [dbo].[RealEstateObject]([RealEstateObjectID]) ON DELETE CASCADE
ALTER TABLE [dbo].[RealEstateObject] ADD CONSTRAINT [FK_dbo.RealEstateObject_dbo.Person_AgentRefID] FOREIGN KEY ([AgentRefID]) REFERENCES [dbo].[Person]([PersonID])
ALTER TABLE [dbo].[RealEstateObject] ADD CONSTRAINT [FK_dbo.RealEstateObject_dbo.City_CityRefID] FOREIGN KEY ([CityRefID]) REFERENCES [dbo].[City]([CityID]) ON DELETE CASCADE
System.Data.SqlClient.SqlException (0x80131904): Introducing FOREIGN KEY constraint 'FK_dbo.RealEstateObject_dbo.City_CityRefID' on table 'RealEstateObject' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClass30.<ExecuteStatements>b__2e()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.<Update>b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update(String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
ClientConnectionId:7baa675e-4667-4db2-b607-adc35067f768
Error Number:1785,State:0,Class:16
Introducing FOREIGN KEY constraint 'FK_dbo.RealEstateObject_dbo.City_CityRefID' on table 'RealEstateObject' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint or index. See previous errors.

**Comment by RobinLjungqvist** [comment]
We removed the decorations/annotations for the foreign keys and the constraint issue resolved itself.

**Comment by mondeun** [comment]
Cool story bro.

**Comment by RobinLjungqvist** [comment]
Haha måste ju testa :3

Den 26 apr 2016 16:33 skrev "Kenneth G" notifications@github.com:
